### ISSUE TITLE
Improving competencies view in Credential Finder through contextualization

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/Credential-Finder#1]
**Note: I've created this repo because we have none that directly address issues with the [Credential Finder](https://credentialfinder.com/).**

@Lomilar, @jkitchensSIUC, @cwd-mparsons, @siuc-nate:

While I am positive we had a linked set of issues on this matter both here an in CASS-Editor, I can't find them. Many weeks back during one of the CASS calls we discussed what might be done to improve the utility of the flat lists of competencies assigned to resources in the Credential Finder. Currently, they look like the following:

<img width="1511" alt="screenshot 2018-07-15 15 43 52" src="https://user-images.githubusercontent.com/2939046/42739198-5312c282-8847-11e8-8cc2-6056863aa729.png">
 
We discussed a few options and I demo'd the LD4PE Explorer at http://explore.dublincore.net/explore-learning-resources-by-competency/ --a repository of Linked Data learning resources mapped to the "Competency Index for Linked Data". Below is a record image that has a flat set of competencies assigned with the cursor hovering over one competency revealing a partial context in a greyed box Users find something as minimal as this helpful in understanding the competency.    

<img width="892" alt="screenshot 2018-07-15 15 57 45" src="https://user-images.githubusercontent.com/2939046/42739241-5224b2a8-8848-11e8-9d90-a4f9e3d7fef5.png">

We need something like this to better contextualize the frequently long competency lists.

**Comment by siuc-nate** [comment]
This might be a nicer way to handle it - we would only need to get the JSON for each framework that the credential has something to do with (which I think we're already retrieving) and display the related snippet.  Then we wouldn't have to try to shoehorn a read-only view via the CASS editor into the space alotted by the modal window on the detail page.

**Comment by siuc-nate** [comment]
The competency view has since been contextualized.
